version: '3.7'

services:
  telegram:
    build:
      context: .

    environment:
      - STORAGE_TYPE=file
      - STORAGE_PATH=media
      - SECRET_KEY=secret

    volumes:
      - ./media:/media
